---
layout: post
#标题配置
title:  彻底理解 promise
#时间配置
date:   2021-04-21 09:25:00 +0800
#大类配置
categories: es6 基础
#小类配置
tag: promise
---

* content
{:toc}

准备工作
====

同步回调
----
```js
const arr = [1,2,3];
arr.forEach(item => { // 遍历回调
    console.log(item);
})
console.log('回调之后');
```

异步回调
----

```js
setTimeout(()=>{ // 异步回调函数，会放入队列中后在执行
    console.log('timeout callback()');
}, 0);
console.log('setTimeout 之后');
```

js 常见内置错误
----

抛出错误：
1、 ReferenceError： 引用变量不存在，中断执行
2、 TypeError： 数据类型不存在
3、 RangeError：数据值不在其所允许的范围
4、 SyntaxError：语法错误

> 错误处理

1. 捕获错误：

```js
try{
    let d;
    console.log(d.xxx);
} catch (error){
    console.log(error.message);
    console.log(error.stack);
}
```

2. 抛出错误

```js
function something() {
    if(Date.now() % 2 === 1) {
        console.log('当前时间为基数');
    } else { // 自己决定错误，让下级去做处理
        throw new Error('当前时间为偶数，无法执行任务');
    }
}
try {
    something();
} catch (error) {
    console.log(error);
}
```

回调地狱解决方案
-----
1. promise.then()

但是由于 then() 需要等待 promise 的结果，所以这种实现方式不是最终极的解决方案。

2. async/await

终极解决方案，配合 promise 使用更佳。

API
=====

捕获错误
-----
由于错误穿透，所以可通过两种方式捕获错误。
```js
new Promise ((resolve, reject) => {
    resolve()
}
).then( (value)=>{
    console.log('onResolved', value);
}
).catch( (reason) => {
    console.log('onReject', reason);
})
```
相当于这么写

```js
new Promise ((resolve, reject) => {
    resolve()
}
).then( 
    (value)=>{
        console.log('onResolved', value);
    },
    (reason) => {
        console.log('onReject', reason);
        throw reason;
    }   
)
```

中断 promise 链
----
当上一个 promise 返回的是 pending 状态时，就中断链式promise

```js
new Promise ((resolve, reject) => {
    resolve()
}
).then( 
    (value)=>{
        console.log('onResolved', value);
        return new Promise(()=>{}) // 即可中断 promise 链，下面的那个不执行
    },  
).then( 
    (value)=>{
        console.log('onResolved1', value);
    },
    (reason) => {
        console.log('onReject1', reason);
    }   
)
```


手写 promise 
=====
1. 构造函数实现

2. then、catch 实现

3. resolve、reject 实现

```js
// 自定义函数模块
(function(){

    function Promise(executor){
        const self = this;
        const PENDING = 'pending';
        const RESOLVED = 'resolved';
        const REJECTED = 'rejected'
        self.status = PENDING;
        self.data = undefined;
        self.callbacks = [];
        // 立即同步执行执行器函数
        function resolve(value) {
            // 如果当前状态不是 pending，直接结束
            if(self.status !== PENDING) {
                return;
            }
            
            // 将状态改为 resolve
            self.status = RESOLVED;
            // 保存 value 数据
            self.data = value;
            // 如果有待执行 callback 函数，立即异步执行回调函数
            if(self.callbacks.length > 0) {
                setTimeout(()=>{
                    self.callbacks.forEach( callbacksObj => {
                        callbacksObj.onResolved(value);
                    })
                })
            }
        }
        function reject(reason) {
            // 如果当前状态不是 pending，直接结束
            if(self.status !== PENDING) {
                return;
            }

            // 将状态改为 rejected
            self.status = RESOLVED;
            // 保存 reason 数据
            self.data = reason;
            // 如果有待执行 callback 函数，立即异步执行回调函数 onRejected
            if(self.callbacks.length > 0) {
                setTimeout(()=>{
                    self.callbacks.forEach( callbacksObj => {
                        callbacksObj.onRejected(reason);
                    })
                })
            }
        }
        try {
            executor(resolve, reject)
        
        } catch (error) { // 如果执行器抛出异常，promise 改为 rejected
            reject(error)
        }
    
    }

    // promise 原型上的 then
    Promise.prototype.then = function(onResolved, onRejected) {
        onResolved = typeof onResolved === 'function' ? onResolved : value => value;
        // 指定默认函数的失败回调（实现错误、异常穿透的关键点）
        onRejected = typeof onRejected === 'function' ? onRejected : reason => {throw reason};

        function handle(callback) {
            /**
            1. 如果执行抛出异常，return 的 promise 就会失败，失败的 reason 就是 error
            2. 如果回调函数执行返回不是 promise ， return 的 promise 就会成功，value就是返回值
            3. 如果回调函数执行返回是 promise ， return 的 promise 就是这个 promise 的结果
            */
            try{
                const result = callback(self.data);
                // 如果回调函数执行返回是 promise ， return 的 promise 就是这个 promise 的结果
                if(result instanceof Promise) {
                    // result.then(
                    //     value => resolve(value), // result 成功时，让 return 的promise 也成功
                    //     reason => reject(reason)// result 失败时，让 return 的promise 也失败
                    // )
                    result.then(resolve，reject);// result 失败时，让 return 的promise 也失败
                } else {
                    // 如果回调函数执行返回不是 promise ， return 的 promise 就会成功，value就是返回值
                    resolve(result)
                }
            
            } catch (error) {
                reject(error);
            }
        
        }

        const self = this;
        return new Promise( (resolve, reject)=>{
            if(self.status === PENDING) {
                // 当前状态是 pending 状态
                self.callbacks.push({
                    onResolved(value){
                        handle(onResolved);
                    }, 
                    onRejected(){
                        handle(onRejected);
                    }
                })
            } else if (self.status === RESOLVED) {
                // 当前状态是 resolved 状态, 异步执行 onResolved，并改变 return 的 promise 状态

                setTimeout(()=>{
                    handle(onResolved);
                });
            } else {
                // 当前状态是 rejected 状态, 异步执行 onRejected，并改变 return 的 promise 状态
                setTimeout(()=>{
                    handle(onRejected);
                });
            }
        
        })
        

    }
    // promise 原型上的 catch
    Promise.prototype.catch = function(onRejected) {
        return this.then(undefined, onRejected);
    }

    // 函数对象上的 resolve 方法
    Promise.resolve = function (value) {
        return new Promise((resolve, reject) =>{
            if(value instanceof Promise) { // 使用 value 作为 promise 的结果
                value.then(resolve, reject);
            } else { // value 不是 promise，那么结果就是 value
                resolve(value);
            }
        })
    }
        
    // 函数对象上的 reject 方法 
    Promise.reject = function (reason) {
        return new Promise((resolve, reject) =>{
            reject(reason);
        })
    }

    // 函数对象上的 all 方法  promises 指 promise 数组
    Promise.all = function (promises) {
        
    }

    // 函数对象上的 race 方法  promises 指 promise 数组
    Promise.race = function (promises) {
        
    }
    window.Promise = Promise;
})(window)
```

